version: '3.8'

services:
  algovision-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "8000:8000"  # API port
      - "5678:5678"  # Debugger port
    volumes:
      - ./uploads:/workspace/uploads
      - ./frames:/workspace/frames
      - ./outputs:/workspace/outputs
      - ./inputs:/workspace/inputs
      - ./app:/workspace/app  # Mount source code for live editing
    environment:
      - PYTHONPATH=/workspace
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu] 